# Generated Documentation Config
springdoc:
  swagger-ui:
    path: /docs

# Spring Config
spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://postgres_db_security_demo:5432/security_demo
    username: dev-ninja
    password: ujac8ozJExiHFfcTNPd6
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

# Server Config
server:
  http2:
    enabled: true
  port: ${PORT:8080}
  servlet:
    context-path: /security-db-demo/api
